version: "3.9"
services:
  admin:
    platform: linux/amd64
    container_name: admin
   #Need to update
    image: .dkr.ecr.ap-southeast-2.amazonaws.com/admin:latest
    build: ./admin
    ports:
      - "80:80"
    networks:
      pharmacy_app:
        ipv4_address: 172.20.0.11
  api:
    platform: linux/amd64
    #Need to update
    image: .dkr.ecr.ap-southeast-2.amazonaws.com/api:latest
    container_name: api
    ports:
      - "80:80"
    build: ./api
    environment:
    networks:
      pharmacy_app:
        ipv4_address: 172.20.0.12
networks:
  pharmacy_app:
    ipam:
      config:
        - subnet: 172.20.0.0/16
